version: '2'
services:
  bon:
    extends:
      file: docker-compose.bon.yml
      service: bon

  pcscd:
    build:
      context: ./pcscd
      args:
        DEBIAN_TAG: buster-slim
    image: 68fpjc/pcscd-buster
    privileged: true
    environment:
      TZ: Asia/Tokyo
    volumes:
      - /var/run/pcscd/
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'

  mirakc:
    build:
      context: ./mirakc
      args:
        ME: ${USER}
    image: 68fpjc/mirakc
    depends_on:
      - bon
      - pcscd
    environment:
      TZ: Asia/Tokyo
      # Log level of `mirakc`.
      # See README.md in masnagam/mirakc.
      RUST_LOG: info
      # Output info-level log messages from child processes like
      # `mirakc-arib collect-eits` for debugging purpose.
      #
      # Normally, you don't need to define the following environment variables.
      MIRAKC_DEBUG_CHILD_PROCESS: ''
      MIRAKC_ARIG_LOG: info
    volumes:
      - ./mirakc/mirakc-config.yml:/etc/mirakc/config.yml:ro
      - ./mirakc/epg/:/var/lib/mirakc/epg/
      - ./bonconf/:/var/lib/BonDriverProxy_Linux/config.in/:ro
    volumes_from:
      - pcscd
    ports:
      - "40772:40772"
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
