version: '3.4'
services:
  bon:
    build:
      context: ./bon
    image: 68fpjc/bondriverproxy
    environment:
      TZ: Asia/Tokyo
      BONDRIVERPROXY_USELNB: 0,1
    devices:
      - /dev/px4video0:/dev/pt3video0
      - /dev/px4video1:/dev/pt3video1
      - /dev/px4video2:/dev/pt3video2
      - /dev/px4video3:/dev/pt3video3
      # - /dev/px4video4:/dev/pt3video4
      # - /dev/px4video5:/dev/pt3video5
      # - /dev/px4video6:/dev/pt3video6
      # - /dev/px4video7:/dev/pt3video7
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    ports:
      - "1192:1192"
    restart: unless-stopped

  pcscd:
    build:
      context: ./pcscd
      args:
        DEBIAN_TAG: stretch-slim
    image: 68fpjc/pcscd:stretch-slim
    privileged: true
    environment:
      TZ: Asia/Tokyo
    volumes:
      - pcscd:/var/run/pcscd/
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    restart: unless-stopped

  mirakurun:
    build:
      context: ./mirakurun
      target: mirakurun
      args:
        - BASE=keymetrics/pm2:10-slim
        - MIRAKURUN_VER=2.14.0
    image: 68fpjc/mirakurun:2.14.0
    depends_on:
      - bon
      - pcscd
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    environment:
      TZ: Asia/Tokyo
    volumes:
      - pcscd:/var/run/pcscd/
      - ./mirakurun/conf/:/usr/local/etc/mirakurun/
      - ./mirakurun/db/:/usr/local/var/db/mirakurun/
      - ./bonconf/:/var/lib/BonDriverProxy_Linux/config.in/:ro
    ports:
      - "40772:40772"
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    restart: unless-stopped

volumes:
  pcscd: