version: '3.4'
services:
  bon:
    build:
      context: ./dockerfiles/bon
    image: 68fpjc/bondriverproxy
    environment:
      TZ: Asia/Tokyo
      BONDRIVERPROXY_USELNB: 0,1
    devices:
      - /dev/px4video0:/dev/pt3video0
      - /dev/px4video1:/dev/pt3video1
      - /dev/px4video2:/dev/pt3video2
      - /dev/px4video3:/dev/pt3video3
      # - /dev/px4video4:/dev/pt3video4
      # - /dev/px4video5:/dev/pt3video5
      # - /dev/px4video6:/dev/pt3video6
      # - /dev/px4video7:/dev/pt3video7
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    ports:
      - "1192:1192"
    restart: unless-stopped

  mirakurun:
    build:
      context: ./dockerfiles/mirakurun
      target: mirakurun
      args:
        - BASE=chinachu/mirakurun:3.3.1
    image: 68fpjc/mirakurun:3.3.1
    depends_on:
      - bon
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./data/mirakurun/opt/:/opt/
      - ./data/mirakurun/config/:/app-config/
      - ./data/mirakurun/data/:/app-data/
      - ./data/bon/:/var/lib/BonDriverProxy_Linux/config.in/:ro
      - ./data/mirakurun/config/sample.tuners.yml:/app/config/tuners.yml:ro
      - ./data/mirakurun/config/sample.channels.yml:/app/config/channels.yml:ro
    ports:
      - "40772:40772"
      - "9229:9229"
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    restart: unless-stopped
