version: '2'
services:
  bon:
    extends:
      file: docker-compose.bon.yml
      service: bon

  pcscd:
    build:
      context: ./pcscd
      args:
        DEBIAN_TAG: stretch-slim
    image: 68fpjc/pcscd:stretch-slim
    privileged: true
    environment:
      TZ: Asia/Tokyo
    volumes:
      - /var/run/pcscd/
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    restart: unless-stopped

  mirakurun:
    build:
      context: ./mirakurun
      args:
        - MIRAKURUN_VER=2.13.0
    image: 68fpjc/mirakurun:2.13.0
    depends_on:
      - bon
      - pcscd
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./mirakurun/conf/:/usr/local/etc/mirakurun/
      - ./mirakurun/db/:/usr/local/var/db/mirakurun/
      - ./bonconf/:/var/lib/BonDriverProxy_Linux/config.in/:ro
    volumes_from:
      - pcscd
    ports:
      - "40772:40772"
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    restart: unless-stopped
