version: '3.4'
services:
  bon:
    build:
      context: ./dockerfiles/bon
    image: 68fpjc/bondriverproxy:2021-03-02
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./data/bon/driver/:/var/lib/BonDriverProxy_Linux/config.in/:ro
    devices:
      - /dev/px4video0:/dev/px4video0
      - /dev/px4video1:/dev/px4video1
      - /dev/px4video2:/dev/px4video2
      - /dev/px4video3:/dev/px4video3
      # - /dev/px4video4:/dev/px4video4
      # - /dev/px4video5:/dev/px4video5
      # - /dev/px4video6:/dev/px4video6
      # - /dev/px4video7:/dev/px4video7
      # - /dev/dvb:/dev/dvb
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    ports:
      - "1192:1192"
    restart: unless-stopped

  mirakurun:
    build:
      context: ./dockerfiles/mirakurun
      target: mirakurun
      args:
        - BASE=chinachu/mirakurun:3.5.0
    image: 68fpjc/mirakurun:3.5.0
    depends_on:
      - bon
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./data/mirakurun/opt/:/opt/
      - ./data/mirakurun/config/:/app-config/
      - ./data/mirakurun/data/:/app-data/
      - ./data/bon/client/:/var/lib/BonDriverProxy_Linux/config.in/:ro
      - ./data/mirakurun/config/sample.tuners.yml:/app/config/tuners.yml:ro
      - ./data/mirakurun/config/sample.channels.yml:/app/config/channels.yml:ro
    ports:
      - "40772:40772"
      - "9229:9229"
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    restart: unless-stopped

  mirakc:
    build:
      context: ./dockerfiles/mirakc
      target: mirakc
      args:
        - BASE=mirakc/mirakc:0.17.3-debian
    image: 68fpjc/mirakc:0.17.3
    depends_on:
      - bon
    environment:
      TZ: Asia/Tokyo
      # Log level of `mirakc`.
      # See README.md in mirakc/mirakc.
      RUST_LOG: info
      # Output info-level log messages from child processes like
      # `mirakc-arib collect-eits` for debugging purpose.
      #
      # Normally, you don't need to define the following environment variables.
      MIRAKC_DEBUG_CHILD_PROCESS: ''
      MIRAKC_ARIG_LOG: info
    volumes:
      - ./data/mirakc/config.yml:/etc/mirakc/config.yml:ro
      - ./data/mirakc/epg/:/var/lib/mirakc/epg/
      - ./data/bon/client/:/var/lib/BonDriverProxy_Linux/config.in/:ro
    ports:
      - "40772:40772"
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    restart: unless-stopped
