version: '2'
services:
  bon:
    build:
      context: ./bon
    image: 68fpjc/bondriverproxy
    environment:
      TZ: Asia/Tokyo
      BONDRIVERPROXY_USELNB: 0,1
    devices:
      - /dev/px4video0:/dev/pt3video0
      - /dev/px4video1:/dev/pt3video1
      - /dev/px4video2:/dev/pt3video2
      - /dev/px4video3:/dev/pt3video3
      # - /dev/px4video4:/dev/pt3video4
      # - /dev/px4video5:/dev/pt3video5
      # - /dev/px4video6:/dev/pt3video6
      # - /dev/px4video7:/dev/pt3video7
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '5'
    ports:
      - "1192:1192"
    restart: unless-stopped
